default: &default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["DB_USER_PASSWORD"] %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: retaurant_online_development

test:
  <<: *default  
  database: retaurant_online_test

production:
  <<: *default
  database: retaurant_online_production